platform :ios, "7.0"

pod 'SVProgressHUD','~> 1.1.3'
pod 'AFNetworking','~> 2.6.0'
pod 'IQKeyboardManager'
pod 'Masonry', '~> 0.6'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'SDCycleScrollView','~> 1.3'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJRefresh', '~> 2.4.12'
